valery: homework 4 completed
eugene-okulik/Valery pull request #3
Opened 2024-12-05 08:20 UTC by v-kaptanouski

2024-12-05 17:57 UTC, eugene-okulik requested changes

2024-12-05 17:57 UTC, eugene-okulik commented on homework/valery_kaptanouski/Homework_4/task4_1.py
> +my_dict['list'].pop(2)
нужно было удалить второй элемент, а ты удалил третий

2024-12-05 17:57 UTC, eugene-okulik commented on homework/valery_kaptanouski/Homework_4/task4_1.py
> +my_dict['dict']["i am a tuple"] = (9, 8, 7, 6, 5)
В задании было:

> добавьте элемент с ключом ('i am a tuple',) и любым значением

У тебя выполнено как если бы там было

> добавьте элемент с ключом 'i am a tuple' и любым значением

`('i am a tuple',) ` - кортеж с одним элементом. И именно это и должно быть ключом. Сейчас ключ - строка `'i am a tuple'`

2024-12-06 06:15 UTC, v-kaptanouski commented on homework/valery_kaptanouski/Homework_4/task4_1.py
> +my_dict['list'].pop(2)
Поменял индекс

2024-12-06 06:16 UTC, v-kaptanouski commented on homework/valery_kaptanouski/Homework_4/task4_1.py
> +my_dict['dict']["i am a tuple"] = (9, 8, 7, 6, 5)
Добавил в ключ кортеж

2024-12-06 06:46 UTC, eugene-okulik requested changes

2024-12-06 06:46 UTC, eugene-okulik commented on homework/valery_kaptanouski/Homework_4/task4_1.py
> +my_dict['dict']["(i am a tuple)"] = (9, 8, 7, 6, 5)
Теперь ты сделал ключом сроку `"(i am a tuple)"`, а нужно, чтобы ключом был кротеж из одного элемента `("i am a tuple",)`

2024-12-06 15:38 UTC, v-kaptanouski commented on homework/valery_kaptanouski/Homework_4/task4_1.py
> +my_dict['dict']["(i am a tuple)"] = (9, 8, 7, 6, 5)
посмотри пожалуйста [этот](https://github.com/eugene-okulik/Valery/pull/3/commits/ac7b660a67d81936f8f05872a04038fcccd6a984) коммит

2024-12-07 09:18 UTC, eugene-okulik approved these changes

2024-12-07 09:18 UTC, merged